name: Update native version used

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Define the specific release version?
        required: true
      release_type:
        description: Specify the release type
        required: true
        options:
          - minor
          - patch
      platform:
        type: choice
        description: Specify the platform to be updated
        required: true
        options:
          - android
          - ios
jobs:
  update_android_native_version:
    if: ${{ github.event.inputs.platform == 'android' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{steps.generate_token.outputs.token}}
      - name: "Update the android version"
        run: sed -i 's/implementation "com.bandyer:bandyer-android-sdk:[0-9]*\.[0-9]*\.[0-9]*-*\w*"/implementation "com.bandyer:bandyer-android-sdk:'${{ github.event.inputs.release_version }}'"/g' ./android/build.gradle
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: update_native
          commit_message: "chore: Update android sdk version"
          tagging_message: android-v${{ github.event.inputs.release_version }}

  update_ios_native_version:
    if: ${{ github.event.inputs.platform == 'ios' }}
    runs-on: macos-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{steps.generate_token.outputs.token}}
      - name: "Update the ios version"
        run: |
            sed -i '' "s/pod 'Bandyer', '~> [0-9]*\.[0-9]*\.[0-9]*-*\w*'/ pod 'Bandyer', '~> "${{ github.event.inputs.release_version }}"'/g" ./iOS/Podfile
            cd iOS
            pod install --repo-update
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: update_native
          commit_message: "chore: Update ios sdk version"
          tagging_message: ios-v${{ github.event.inputs.release_version }}
  
  create_pull_request:
    runs-on: ubuntu-latest
    needs: [update_android_native_version, update_ios_native_version]
    if: ${{ always() && !cancelled() && !contains(needs.*.result, 'failure') }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{steps.generate_token.outputs.token}}
      - name: Reset update_native branch
        run: |
          git fetch origin update_native:update_native
          git reset --hard update_native
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{steps.generate_token.outputs.token}}
          commit-message: 'chore: Update native version'
          branch: prepare_release_native
          title: 'Update native dependency'
          labels: |
              ${{ github.event.inputs.release_type }}
